// Generated by scripts/recovery/generate-shims.mjs. A compat shim is correct when every old name IS the owner's export.
import test from "node:test";
import assert from "node:assert/strict";
import * as shim0 from "../dist/index.js";
import * as owner0 from "obix-core-oop";

test("obix-adapter-oop: every old name is the owner's export, and nothing else is exported", () => {
  assert.equal(shim0["toOOP"], owner0["toOOP"], "toOOP");
  assert.deepEqual(Object.keys(shim0).sort(), ["toOOP"]);
});
