// Generated by scripts/recovery/generate-shims.mjs — a compat shim: no logic, only the owner's exports under the old names.
export { toOOP } from "obix-core-oop";
export type { OOPConstructor, OOPInstance } from "obix-core-oop";
